---
Attribute:
  enabled: true
  exclude:
  - Veritas::Optimizer
  - Veritas::Optimizer::Algebra::Extension
  - Veritas::Optimizer::Algebra::Rename
  - Veritas::Optimizer::Algebra::Restriction
  - Veritas::Optimizer::Algebra::Summarization
  - Veritas::Optimizer::Function::Binary
  - Veritas::Optimizer::Function::Unary
  - Veritas::Optimizer::Optimizable::ClassMethods
  - Veritas::Optimizer::PredicatePartition
  - Veritas::Optimizer::Relation::Operation::Unary
BooleanParameter:
  enabled: true
  exclude: []
ClassVariable:
  enabled: true
  exclude: []
ControlParameter:
  enabled: true
  exclude: []
DataClump:
  enabled: true
  exclude: []
  max_copies: 2
  min_clump_size: 2
DuplicateMethodCall:
  enabled: true
  exclude:
  - Veritas::Optimizer::Algebra::Difference::EqualOperands#optimize
  - Veritas::Optimizer::Algebra::Join::MaterializedLeft#right_matching_left?
  - Veritas::Optimizer::Algebra::Join::MaterializedRight#left_matching_right?
  - Veritas::Optimizer::Algebra::Product::TableDeeLeft#optimizable?
  - Veritas::Optimizer::Algebra::Product::TableDeeRight#optimizable?
  - Veritas::Optimizer::Algebra::Projection::ExtensionOperand#optimizable?
  - Veritas::Optimizer::Algebra::Rename::ProjectionOperand#removed_attributes
  - Veritas::Optimizer::Algebra::Restriction::CombinationOperand#partition
  - Veritas::Optimizer::Algebra::Restriction::Contradiction#optimize
  - Veritas::Optimizer::Algebra::Summarization::EmptySummarizePer#optimize
  - Veritas::Optimizer::Function::Connective::Binary#contradiction?
  - Veritas::Optimizer::Function::Connective::Binary#contradiction?
  - Veritas::Optimizer::Function::Connective::Binary#left_equality?
  - Veritas::Optimizer::Function::Connective::Binary#left_inequality?
  - Veritas::Optimizer::Function::Connective::Binary#right_equality?
  - Veritas::Optimizer::Function::Connective::Binary#right_inequality?
  - Veritas::Optimizer::Function::Connective::Binary::RedundantLeft#optimizable?
  - Veritas::Optimizer::Function::Connective::Binary::RedundantRight#optimizable?
  - Veritas::Optimizer::Function::Predicate::Comparable::NeverEquivalent#joinable?
  - Veritas::Optimizer::Function::Predicate::Enumerable#optimize_right_range
  - Veritas::Optimizer::Function::Predicate::GreaterThanOrEqualTo::Tautology#optimizable?
  - Veritas::Optimizer::Function::Predicate::LessThanOrEqualTo::Tautology#optimizable?
  - Veritas::Optimizer::Relation::Materialized::EmptyOperand#optimize
  - Veritas::Optimizer::Relation::Operation::Combination#optimize
  - Veritas::Optimizer::Relation::Operation::Limit::ZeroLimit#optimize
  - Veritas::Optimizer::Relation::Operation::Order::OneLimitOperand#optimizable?
  max_calls: 1
  allow_calls: []
FeatureEnvy:
  enabled: true
  exclude: []
IrresponsibleModule:
  enabled: true
  exclude: []
LongParameterList:
  enabled: true
  exclude: []
  max_params: 2
  overrides:
    initialize:
      max_params: 3
LongYieldList:
  enabled: true
  exclude: []
  max_params: 2
NestedIterators:
  enabled: true
  exclude: []
  max_allowed_nesting: 1
  ignore_iterators: []
NilCheck:
  enabled: true
  exclude:
  - Veritas::Optimizer::Function::Predicate::Comparable::NeverEquivalent#nil_operand?
  - Veritas::Optimizer::Function::Predicate::Enumerable::EmptyRight#right_nil?
  - Veritas::Optimizer::Function::Util#self.constant?
RepeatedConditional:
  enabled: true
  exclude: []
  max_ifs: 1
TooManyInstanceVariables:
  enabled: true
  exclude:
  - Veritas::Optimizer::PredicatePartition
  max_instance_variables: 3
TooManyMethods:
  enabled: true
  exclude:
  - Veritas::Optimizer::Function::Connective::Binary
  max_methods: 10
TooManyStatements:
  enabled: true
  exclude:
  - Veritas::Optimizer#self.link_optimizers
  - Veritas::Optimizer::Algebra::Projection::ExtensionOperand#new_extensions
  - Veritas::Optimizer::Algebra::Summarization::EmptyOperand#extensions
  - Veritas::Optimizer::Function#self.optimize_functions
  - Veritas::Optimizer::Function::Predicate::Comparable::NeverComparable#optimizable?
  - Veritas::Optimizer::Function::Predicate::Comparable::NeverEquivalent#optimizable?
  - Veritas::Optimizer::Function::Predicate::Enumerable#normalized_right_enumerable
  - Veritas::Optimizer::Function::Predicate::Enumerable#optimize_right
  - Veritas::Optimizer::Function::Predicate::Enumerable#optimize_right_enumerable
  - Veritas::Optimizer::Function::Predicate::Enumerable#optimize_right_range
  - Veritas::Optimizer::Optimizable#optimize
  - Veritas::Optimizer::PredicatePartition#partition!
  - Veritas::Optimizer::PredicatePartition#partition_binary!
  - Veritas::Optimizer::PredicatePartition#partition_proposition!
  - Veritas::Optimizer::PredicatePartition#partition_unary!
  max_statements: 2
UncommunicativeMethodName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^[a-z]$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UncommunicativeModuleName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  accept: []
UncommunicativeParameterName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UncommunicativeVariableName:
  enabled: true
  exclude: []
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
  accept: []
UnusedParameters:
  enabled: true
  exclude: []
UtilityFunction:
  enabled: true
  exclude:
  - Veritas::Optimizer::Function::Connective::Conjunction::Contradiction#optimize
  - Veritas::Optimizer::Function::Connective::Disjunction::Tautology#optimize
  - Veritas::Optimizer::Function::Predicate::Contradiction#optimize
  - Veritas::Optimizer::Function::Predicate::Tautology#optimize
  max_helper_calls: 0
